# Generated by Django 4.1.7 on 2023-03-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_topic_room_host_alter_room_name_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
